apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: pi-soyosa
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
      nodePort: 30092
  type: NodePort
