apiVersion: v1
kind: Service

metadata:
  name: course-service
  namespace: pi-soyosa

spec:
  selector:
    app: courses-microservice

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP
