apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8761'
    prometheus.io/scrape: 'true'
  name: eureka-server
  namespace: pi-soyosa
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server
  type: ClusterIP
