pipeline {
    agent any

    tools {
        nodejs 'NODE_HOME'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                dir('Frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Frontend') {
                    sh 'npm test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Frontend') {
                    sh 'npm run build'
                }
            }
        }
    }
}
