export const countries = [
    { name: 'Afghanistan', iso2: 'af', code: '+93', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Albania', iso2: 'al', code: '+355', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Algeria', iso2: 'dz', code: '+213', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Andorra', iso2: 'ad', code: '+376', length: 6, pattern: '^[0-9]{6}$' },
    { name: 'Angola', iso2: 'ao', code: '+244', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Argentina', iso2: 'ar', code: '+54', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Armenia', iso2: 'am', code: '+374', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Australia', iso2: 'au', code: '+61', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Austria', iso2: 'at', code: '+43', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Azerbaijan', iso2: 'az', code: '+994', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Bahrain', iso2: 'bh', code: '+973', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Bangladesh', iso2: 'bd', code: '+880', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Belarus', iso2: 'by', code: '+375', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Belgium', iso2: 'be', code: '+32', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Benin', iso2: 'bj', code: '+229', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Bolivia', iso2: 'bo', code: '+591', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Bosnia and Herzegovina', iso2: 'ba', code: '+387', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Brazil', iso2: 'br', code: '+55', length: 11, pattern: '^[0-9]{11}$' },
    { name: 'Bulgaria', iso2: 'bg', code: '+359', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Burkina Faso', iso2: 'bf', code: '+226', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Cameroon', iso2: 'cm', code: '+237', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Canada', iso2: 'ca', code: '+1', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Chile', iso2: 'cl', code: '+56', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'China', iso2: 'cn', code: '+86', length: 11, pattern: '^[0-9]{11}$' },
    { name: 'Colombia', iso2: 'co', code: '+57', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Congo', iso2: 'cg', code: '+242', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Costa Rica', iso2: 'cr', code: '+506', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Croatia', iso2: 'hr', code: '+385', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Cuba', iso2: 'cu', code: '+53', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Cyprus', iso2: 'cy', code: '+357', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Czech Republic', iso2: 'cz', code: '+420', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Denmark', iso2: 'dk', code: '+45', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Dominican Republic', iso2: 'do', code: '+1', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Ecuador', iso2: 'ec', code: '+593', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Egypt', iso2: 'eg', code: '+20', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'El Salvador', iso2: 'sv', code: '+503', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Estonia', iso2: 'ee', code: '+372', length: 7, pattern: '^[0-9]{7,8}$' },
    { name: 'Ethiopia', iso2: 'et', code: '+251', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Finland', iso2: 'fi', code: '+358', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'France', iso2: 'fr', code: '+33', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Gabon', iso2: 'ga', code: '+241', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Gambia', iso2: 'gm', code: '+220', length: 7, pattern: '^[0-9]{7}$' },
    { name: 'Georgia', iso2: 'ge', code: '+995', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Germany', iso2: 'de', code: '+49', length: 11, pattern: '^[0-9]{11}$' },
    { name: 'Ghana', iso2: 'gh', code: '+233', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Greece', iso2: 'gr', code: '+30', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Guatemala', iso2: 'gt', code: '+502', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Guinea', iso2: 'gn', code: '+224', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Haiti', iso2: 'ht', code: '+509', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Honduras', iso2: 'hn', code: '+504', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Hungary', iso2: 'hu', code: '+36', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Iceland', iso2: 'is', code: '+354', length: 7, pattern: '^[0-9]{7}$' },
    { name: 'India', iso2: 'in', code: '+91', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Indonesia', iso2: 'id', code: '+62', length: 10, pattern: '^[0-9]{10,12}$' },
    { name: 'Iran', iso2: 'ir', code: '+98', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Iraq', iso2: 'iq', code: '+964', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Ireland', iso2: 'ie', code: '+353', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Israel', iso2: 'il', code: '+972', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Italy', iso2: 'it', code: '+39', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Jamaica', iso2: 'jm', code: '+1', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Japan', iso2: 'jp', code: '+81', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Jordan', iso2: 'jo', code: '+962', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Kazakhstan', iso2: 'kz', code: '+7', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Kenya', iso2: 'ke', code: '+254', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Kuwait', iso2: 'kw', code: '+965', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Latvia', iso2: 'lv', code: '+371', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Lebanon', iso2: 'lb', code: '+961', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Libya', iso2: 'ly', code: '+218', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Lithuania', iso2: 'lt', code: '+370', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Luxembourg', iso2: 'lu', code: '+352', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Madagascar', iso2: 'mg', code: '+261', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Malaysia', iso2: 'my', code: '+60', length: 9, pattern: '^[0-9]{9,10}$' },
    { name: 'Mali', iso2: 'ml', code: '+223', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Malta', iso2: 'mt', code: '+356', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Mauritania', iso2: 'mr', code: '+222', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Mauritius', iso2: 'mu', code: '+230', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Mexico', iso2: 'mx', code: '+52', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Moldova', iso2: 'md', code: '+373', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Monaco', iso2: 'mc', code: '+377', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Montenegro', iso2: 'me', code: '+382', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Morocco', iso2: 'ma', code: '+212', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Namibia', iso2: 'na', code: '+264', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Nepal', iso2: 'np', code: '+977', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Netherlands', iso2: 'nl', code: '+31', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'New Zealand', iso2: 'nz', code: '+64', length: 8, pattern: '^[0-9]{8,10}$' },
    { name: 'Niger', iso2: 'ne', code: '+227', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Nigeria', iso2: 'ng', code: '+234', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Norway', iso2: 'no', code: '+47', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Oman', iso2: 'om', code: '+968', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Pakistan', iso2: 'pk', code: '+92', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Panama', iso2: 'pa', code: '+507', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Paraguay', iso2: 'py', code: '+595', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Peru', iso2: 'pe', code: '+51', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Philippines', iso2: 'ph', code: '+63', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Poland', iso2: 'pl', code: '+48', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Portugal', iso2: 'pt', code: '+351', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Qatar', iso2: 'qa', code: '+974', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Romania', iso2: 'ro', code: '+40', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Russia', iso2: 'ru', code: '+7', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Rwanda', iso2: 'rw', code: '+250', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Saudi Arabia', iso2: 'sa', code: '+966', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Senegal', iso2: 'sn', code: '+221', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Serbia', iso2: 'rs', code: '+381', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Singapore', iso2: 'sg', code: '+65', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Slovakia', iso2: 'sk', code: '+421', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Slovenia', iso2: 'si', code: '+386', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'South Africa', iso2: 'za', code: '+27', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'South Korea', iso2: 'kr', code: '+82', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Spain', iso2: 'es', code: '+34', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Sri Lanka', iso2: 'lk', code: '+94', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Sudan', iso2: 'sd', code: '+249', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Sweden', iso2: 'se', code: '+46', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Switzerland', iso2: 'ch', code: '+41', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Syria', iso2: 'sy', code: '+963', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Taiwan', iso2: 'tw', code: '+886', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Tanzania', iso2: 'tz', code: '+255', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Thailand', iso2: 'th', code: '+66', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Tunisia', iso2: 'tn', code: '+216', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Turkey', iso2: 'tr', code: '+90', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Uganda', iso2: 'ug', code: '+256', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Ukraine', iso2: 'ua', code: '+380', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'United Arab Emirates', iso2: 'ae', code: '+971', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'United Kingdom', iso2: 'gb', code: '+44', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'United States', iso2: 'us', code: '+1', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Uruguay', iso2: 'uy', code: '+598', length: 8, pattern: '^[0-9]{8}$' },
    { name: 'Uzbekistan', iso2: 'uz', code: '+998', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Venezuela', iso2: 've', code: '+58', length: 10, pattern: '^[0-9]{10}$' },
    { name: 'Vietnam', iso2: 'vn', code: '+84', length: 9, pattern: '^[0-9]{9,10}$' },
    { name: 'Yemen', iso2: 'ye', code: '+967', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Zambia', iso2: 'zm', code: '+260', length: 9, pattern: '^[0-9]{9}$' },
    { name: 'Zimbabwe', iso2: 'zw', code: '+263', length: 9, pattern: '^[0-9]{9}$' }
];