apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8087'
    prometheus.io/scrape: 'true'
  name: tracking-service
  namespace: pi-soyosa
spec:
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: trackingms
  type: ClusterIP
