apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: pi-soyosa
spec:
  selector:
    app: trackingms
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP
