apiVersion: v1
kind: Service
metadata:
  name: ecommerce-insights-worker
  namespace: pi-soyosa
spec:
  selector:
    app: ecommerce-insights-worker
  ports:
    - protocol: TCP
      port: 80 # Placeholder as it's a worker
      targetPort: 80
  type: ClusterIP
