apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: pi-soyosa
spec:
  selector:
    app: blog-microservice
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
  type: ClusterIP
