apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: pi-soyosa
spec:
  selector:
    app: interview-microservice
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
  type: ClusterIP
