spring.application.name=Blog

server.port=8072

spring.datasource.url=jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


cloudinary.cloud-name=dd4zk5jpa
cloudinary.api-key=766346281536821
cloudinary.api-secret=YJOxbChBUoX60Qvsm-aAeYHZwL8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

server.servlet.context-path=/api